name: distiller-env
channels:
    - conda-forge
    - defaults
    - bioconda
dependencies:
    - python=3.9
    - parallel
    - pbgzip
    - lz4-c
    - samtools>=1.16.1
    - sra-tools>=3.0.0
    - fastqc
    - bwa
    - seqtk
    - setuptools
    - pip
    - cython
    - numpy>=1.10
    - pysam>=0.15.0
    - nose
    - pairix
    - fastp
    - pip:
        - cooler>=0.8.11
        - toolz
        - git+https://github.com/open2c/pairtools.git
