name: distiller-env
channels:
    - conda-forge               
    - defaults                  
    - bioconda                  
    - golobor
dependencies:
    - python=3.6
    - parallel
    - pbgzip
    - lz4-c
    - samtools>=1.4
    - sra-tools>=2.8.1
    - fastqc
    - bwa
    - seqtk
    - setuptools 
    - pip
    - cython 
    - numpy 
    - dask
    - nose 
    - pairix
    - pip:
        - cooler>=0.7.1
        - git+https://github.com/mirnylab/pairsamtools
        - toolz
